### ISSUE TITLE
germline filtering?

### ISSUE THREAD

**Issue by SooLee** [viq854/lichee#1]
Hello,

I'm trying lichee with the following command and tab-delimited input file (directory and sample names simplified).

./lichee -build -i ~/LICHeE/input.txt -n 0 -sampleProfile -o ~/LICHeE/S1
# chr    position        description     profile Normal        S1

1       11855012        C/T     01      0       0.5
1       16362543        C/G     01      0       0.0714285714285714
1       16891149        T/C     01      0       0.2
1       16918605        A/C     01      0       0.115384615384615
1       17200050        G/C     01      0       0.5
1       27105541        G/A     01      0       0.189189189189189
...

I'm getting the following error message:

...
*_Filtered as germline:
21      11059912        C/T     01      0.0     0.1
*_Filtered as germline:
21      35172281        C/T     01      0.0     0.0465116279069767
*_Filtered as germline:
22      20304925        T/C     01      0.0     0.5
*_Filtered as germline:
22      20502333        G/A     01      0.0     0.142857142857143
**Filtered as germline:
22      20502354        C/T     01      0.0     0.131578947368421
...

There are 208 SNVs in the input file.
After pre-processing, the input consists of 0 somatic SNVs.

All SNV groups have been filtered out.

Can you help me resolve this? Thank you.

Best,
Soo

**Comment by viq854** [comment]
Hi Soo,

I'll be happy to help you resolve this.

Looks like the issue is with using the "-sampleProfile" flag. With this
flag, the program expects to see an additional column in the input file
which should indicate the presence of the SNVs in each sample. If you
remove this flag, no SNVs will be filtered. However, you will need to
supply the VAF thresholds so that LICHeE can compute the presence profile
itself.

Hope this answers your question. Please let me know if anything else comes
up.

Best,
Victoria

**Comment by SooLee** [comment]
Hi Victoria,

My input files contain the profile column and it is 01 for every line (it's not clear in the text because the columns are not lined up). Did I miss something?

Best,
Soo

**Comment by viq854** [comment]
Hi Soo,

Ah yes, the file looks good (btw, in this case the -n flag should not be needed).
I've updated the code a bit (somehow a local setting didn't make it into my latest commit), please pull and hopefully it should all run fine.

**Comment by SooLee** [comment]
Still getting the same result..

**Comment by viq854** [comment]
Just added the recompiled jar

**Comment by SooLee** [comment]
It works. Thanks!
