### ISSUE TITLE
Output interpretation

### ISSUE THREAD

**Issue by SooLee** [viq854/lichee#3]
Hello,

Can you please help me interpreting the output of LICHeE? I'm seeing the following result, with 0.41 and 0.1 for two subclones, when I gave an input of VAF values of two samples (one normal and one tumor). My VAF histogram for the tumor sample has two peaks, around 0.1 and 0.41 each. I was thinking the second was is probably the clonal and the first one is a subclone. The cellular prevalence would be 20% and 82%, considering that the mutations are heterozygous (the 82% also indicating purity in this case). Would it be correct if I see the 0.1 and 0.41 as mean VAF estimates rather than CP estimates (with the numbers in bracket as standard errors)? 

Sample decomposition: 
Normal:
GL

Tumor:
GL
     01: 0.41 [0.09]
          01: 0.1 [0.03]

Thank you in advance..

Best,
Soo

**Comment by viq854** [comment]
Hi Soo,

Yes you are correct, there are two subclones in the tumor sample (with the CP values being twice the given VAFs; we assume the mutations are heterozygous). Two topologies are valid here: chain (GL --> 0.41 --> 0.1) with no error and branching (GL --> 0.41 & GL --> 0.1) allowing for a small VAF error. The program reports sample decomposition by using indentations in each line to indicate the depth of cluster in the tree. I'm guessing the top tree you are seeing (for the chain topology with no error, highest ranking) gives you the following:

GL
.....01: 0.41 [0.09]  _(1)_
............01: 0.1 [0.03]   _(2)_

Is that correct? In this case you have a subclone with VAF 0.1 containing mutations from clusters _(1)_ and _(2)_ and a subclone of VAF 0.31 containing just mutations from cluster _(1)_. The values in the brackets are the standard deviations of the clusters. Another way to view it is that 82% of cells contain mutations in cluster _(1)_ and a fraction of these cells (20% of the total cells) also contain mutations of cluster _(2)_.

For the branching tree topology, the decomposition would be:

GL
.....01: 0.41 [0.09]  _(1)_
.....01: 0.1 [0.03]   _(2)_

This would correspond to two subclones of VAF 0.1 containing just mutations of cluster _(2)_ and of VAF 0.41 containing just mutations of cluster _(1)_.

Hope this helps. Please let me know if you have any other questions. I could provide more examples if necessary.

Thanks,
Vic

**Comment by SooLee** [comment]
Got it! Thanks for the confirmation. 

Best,
Soo
