### ISSUE TITLE
Selecting values for minVAFPresent and maxVAFAbsent

### ISSUE THREAD

**Issue by Rashesh7** [viq854/lichee#8]
Hi,

I am running LICHeE on WGS data and was wondering if there is a standard way of predicting the minVAFPresent and maxVAFAbsent values that should be used?

Thanks,
Rashesh

**Comment by Bio-wupin** [comment]
Hi,

I also want to ask how to set minVAFPresent and maxVAFAbsent parameters. If I change these two parameters I will get different results. I am not sure which is the most correct.

Thanks,
Pin
